### ISSUE TITLE
[Task] 게시글 작성/수정 페이지

### ISSUE THREAD

**Issue by hande-sof** [codestates/DokDok-client#10]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 제목, 내용 input 작성
2. [x] 이미지 업로드 & 미리보기
3. [x] 책 분류& 거래정보 Select 작성
4. [x] 검색해서 장소 선택 시 지도 미리보기 뜨게 [참고](https://postcode.map.daum.net/guide)

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
