### ISSUE TITLE
[Task] (Advanced) 채팅 페이지

### ISSUE THREAD

**Issue by hande-sof** [codestates/DokDok-client#27]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: fix actions from client redux

### TODO
1. [ ] 챗 컴포넌트 제작
2. [ ] 챗 리스트 컴포넌트 제작
3. [ ] 채팅 인풋 컴포넌트 제작
4. [ ] 다 연결해서 채팅 방 페이지 제작

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
