### ISSUE TITLE
[Task] 리덕스 설정

### ISSUE THREAD

**Issue by hande-sof** [codestates/DokDok-client#3]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] Actions 폴더 생성 & 작성
2. [x] reducers 폴더 생성 & 작성
3. [x] store 폴더 생성 & 작성
3. [x] initState 작성

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__1__`
- Urgency: `High`
